services:
  - type: web
    name: chatify-app
    env: node
    plan: free
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://chatify-app.onrender.com
      # Add your DB and PUSHER keys from the dashboard after creating the service
