services:
  - type: web
    name: chatify-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://chatify-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: db4free.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_db_name
      - key: DB_USERNAME
        value: your_username
      - key: DB_PASSWORD
        value: your_password
      - key: PUSHER_APP_ID
        value: your_pusher_id
      - key: PUSHER_APP_KEY
        value: your_pusher_key
      - key: PUSHER_APP_SECRET
        value: your_pusher_secret
      - key: PUSHER_APP_CLUSTER
        value: your_cluster
